export const assessmentQuestions = {
  // Premium users के लिए आसान प्रश्न
  premium: {
    "Senior Software Engineer": [
      {
        id: 1,
        question: "What does API stand for?",
        options: [
          "Application Programming Interface",
          "Advanced Programming Interface",
          "Application Process Integration",
          "Advanced Process Integration",
        ],
        correctAnswer: 0,
      },
      {
        id: 2,
        question: "Which language is mainly used for web development?",
        options: ["Python", "JavaScript", "Java", "C++"],
        correctAnswer: 1,
      },
      {
        id: 3,
        question: "What is the purpose of a database?",
        options: [
          "To store and organize data",
          "To design websites",
          "To write code",
          "To test applications",
        ],
        correctAnswer: 0,
      },
      {
        id: 4,
        question: "What does OOP stand for?",
        options: [
          "Object-Oriented Programming",
          "Object-Optimized Programming",
          "Operational Object Programming",
          "Organized Object Protocol",
        ],
        correctAnswer: 0,
      },
      {
        id: 5,
        question: "Which data structure uses LIFO principle?",
        options: ["Queue", "Stack", "Array", "Linked List"],
        correctAnswer: 1,
      },
      {
        id: 6,
        question: "What is Git used for?",
        options: [
          "Database management",
          "Version control",
          "Web hosting",
          "Code compilation",
        ],
        correctAnswer: 1,
      },
      {
        id: 7,
        question: "Which protocol is used for websites?",
        options: ["FTP", "HTTP", "SMTP", "TCP"],
        correctAnswer: 1,
      },
      {
        id: 8,
        question: "What does SQL stand for?",
        options: [
          "Structured Query Language",
          "Simple Query Language",
          "Standard Query Language",
          "System Query Language",
        ],
        correctAnswer: 0,
      },
      {
        id: 9,
        question: "What is a variable in programming?",
        options: [
          "A fixed value",
          "A storage location with a name",
          "A function",
          "A data type",
        ],
        correctAnswer: 1,
      },
      {
        id: 10,
        question: "Which of these is a programming language?",
        options: ["HTML", "CSS", "Python", "XML"],
        correctAnswer: 2,
      },
      {
        id: 11,
        question: "What does CSS stand for?",
        options: [
          "Computer Style Sheets",
          "Creative Style System",
          "Cascading Style Sheets",
          "Content Styling System",
        ],
        correctAnswer: 2,
      },
      {
        id: 12,
        question: "What is an algorithm?",
        options: [
          "A programming language",
          "A step-by-step procedure",
          "A hardware component",
          "A database table",
        ],
        correctAnswer: 1,
      },
      {
        id: 13,
        question: "Which tool is used for code editing?",
        options: ["MySQL", "GitHub", "Visual Studio Code", "Docker"],
        correctAnswer: 2,
      },
      {
        id: 14,
        question: "What is debugging?",
        options: [
          "Writing code",
          "Finding and fixing errors",
          "Designing UI",
          "Testing hardware",
        ],
        correctAnswer: 1,
      },
      {
        id: 15,
        question: "What is a compiler?",
        options: [
          "A program that translates code",
          "A type of variable",
          "A database",
          "A networking protocol",
        ],
        correctAnswer: 0,
      },
      {
        id: 16,
        question: "What does IDE stand for?",
        options: [
          "Integrated Development Environment",
          "Internet Development Engine",
          "Interactive Design Environment",
          "Integrated Design Engine",
        ],
        correctAnswer: 0,
      },
      {
        id: 17,
        question: "What is a function in programming?",
        options: [
          "A data type",
          "A reusable block of code",
          "A variable",
          "A database",
        ],
        correctAnswer: 1,
      },
      {
        id: 18,
        question: "Which is a NoSQL database?",
        options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
        correctAnswer: 2,
      },
      {
        id: 19,
        question: "What is cloud computing?",
        options: [
          "Weather forecasting",
          "Delivering computing services over internet",
          "Computer hardware",
          "Programming language",
        ],
        correctAnswer: 1,
      },
      {
        id: 20,
        question: "What is machine learning?",
        options: [
          "Computer repairing",
          "AI that enables computers to learn",
          "Networking protocol",
          "Database management",
        ],
        correctAnswer: 1,
      },
    ],
    "Full Stack Developer": [
      {
        id: 1,
        question: "What does HTML stand for?",
        options: [
          "Hyper Text Markup Language",
          "High Tech Modern Language",
          "Home Tool Markup Language",
          "Hyperlinks and Text Markup Language",
        ],
        correctAnswer: 0,
      },
      {
        id: 2,
        question: "Which tag is used to create a hyperlink in HTML?",
        options: ["<link>", "<a>", "<href>", "<url>"],
        correctAnswer: 1,
      },
      {
        id: 3,
        question: "What is CSS used for?",
        options: [
          "Database management",
          "Styling web pages",
          "Server-side programming",
          "Mobile app development",
        ],
        correctAnswer: 1,
      },
      {
        id: 4,
        question: "What does JavaScript do?",
        options: [
          "Styles web pages",
          "Creates database tables",
          "Adds interactivity to websites",
          "Designs logos",
        ],
        correctAnswer: 2,
      },
      {
        id: 5,
        question: "Which tag is used for JavaScript in HTML?",
        options: ["<java>", "<script>", "<js>", "<javascript>"],
        correctAnswer: 1,
      },
      {
        id: 6,
        question: "What is a responsive website?",
        options: [
          "Fast loading website",
          "Website that works on all devices",
          "Website with animations",
          "E-commerce website",
        ],
        correctAnswer: 1,
      },
      {
        id: 7,
        question: "What is Bootstrap?",
        options: [
          "A programming language",
          "A CSS framework",
          "A database",
          "A server",
        ],
        correctAnswer: 1,
      },
      {
        id: 8,
        question: "What is Node.js?",
        options: [
          "A JavaScript library",
          "JavaScript runtime environment",
          "A database",
          "A CSS framework",
        ],
        correctAnswer: 1,
      },
      {
        id: 9,
        question: "What does DOM stand for?",
        options: [
          "Document Object Model",
          "Data Object Management",
          "Document Order Model",
          "Digital Object Management",
        ],
        correctAnswer: 0,
      },
      {
        id: 10,
        question: "What is React?",
        options: [
          "A database",
          "A JavaScript framework",
          "A programming language",
          "A server",
        ],
        correctAnswer: 1,
      },
      {
        id: 11,
        question: "What is JSON?",
        options: [
          "A programming language",
          "Data format for data interchange",
          "A database",
          "A framework",
        ],
        correctAnswer: 1,
      },
      {
        id: 12,
        question: "What is npm?",
        options: [
          "Node Package Manager",
          "New Programming Method",
          "Network Protocol Manager",
          "Node Program Module",
        ],
        correctAnswer: 0,
      },
      {
        id: 13,
        question: "What is a frontend framework?",
        options: [
          "Database tool",
          "Tool for building user interfaces",
          "Server software",
          "Programming language",
        ],
        correctAnswer: 1,
      },
      {
        id: 14,
        question: "What is MongoDB?",
        options: [
          "SQL database",
          "NoSQL database",
          "Programming language",
          "CSS framework",
        ],
        correctAnswer: 1,
      },
      {
        id: 15,
        question: "What is Express.js?",
        options: [
          "Frontend framework",
          "Backend framework for Node.js",
          "Database",
          "Programming language",
        ],
        correctAnswer: 1,
      },
      {
        id: 16,
        question: "What is a REST API?",
        options: [
          "A database",
          "Architectural style for web services",
          "Programming language",
          "CSS framework",
        ],
        correctAnswer: 1,
      },
      {
        id: 17,
        question: "What is Git?",
        options: [
          "A programming language",
          "Version control system",
          "A framework",
          "A database",
        ],
        correctAnswer: 1,
      },
      {
        id: 18,
        question: "What is a component in React?",
        options: [
          "A database table",
          "Reusable piece of UI",
          "Server configuration",
          "CSS file",
        ],
        correctAnswer: 1,
      },
      {
        id: 19,
        question: "What is TypeScript?",
        options: [
          "A database",
          "JavaScript with static typing",
          "CSS framework",
          "Server software",
        ],
        correctAnswer: 1,
      },
      {
        id: 20,
        question: "What is web hosting?",
        options: [
          "Domain registration",
          "Making website accessible online",
          "Website design",
          "Email service",
        ],
        correctAnswer: 1,
      },
    ],
    "Data Scientist": [
      {
        id: 1,
        question: "What is data science?",
        options: [
          "Database management",
          "Extracting insights from data",
          "Web development",
          "Network security",
        ],
        correctAnswer: 1,
      },
      {
        id: 2,
        question: "Which language is popular for data science?",
        options: ["Java", "C++", "Python", "HTML"],
        correctAnswer: 2,
      },
      {
        id: 3,
        question: "What is a dataset?",
        options: [
          "A collection of data",
          "A programming language",
          "A database server",
          "A statistical method",
        ],
        correctAnswer: 0,
      },
      {
        id: 4,
        question: "What is machine learning?",
        options: [
          "Computer hardware",
          "AI that learns from data",
          "Database management",
          "Web design",
        ],
        correctAnswer: 1,
      },
      {
        id: 5,
        question: "What is Python's pandas library used for?",
        options: [
          "Web development",
          "Data manipulation and analysis",
          "Game development",
          "Mobile apps",
        ],
        correctAnswer: 1,
      },
      {
        id: 6,
        question: "What is NumPy used for?",
        options: [
          "Numerical computing in Python",
          "Web scraping",
          "Database management",
          "UI design",
        ],
        correctAnswer: 0,
      },
      {
        id: 7,
        question: "What is Jupyter Notebook?",
        options: [
          "A database",
          "Web-based interactive computing platform",
          "Programming language",
          "Server software",
        ],
        correctAnswer: 1,
      },
      {
        id: 8,
        question: "What is data visualization?",
        options: [
          "Data storage",
          "Presenting data graphically",
          "Data cleaning",
          "Data collection",
        ],
        correctAnswer: 1,
      },
      {
        id: 9,
        question: "What is matplotlib?",
        options: [
          "A database",
          "Python plotting library",
          "JavaScript framework",
          "CSS framework",
        ],
        correctAnswer: 1,
      },
      {
        id: 10,
        question: "What is SQL used for in data science?",
        options: [
          "Web development",
          "Querying databases",
          "Data visualization",
          "Machine learning",
        ],
        correctAnswer: 1,
      },
      {
        id: 11,
        question: "What is data cleaning?",
        options: [
          "Data visualization",
          "Removing errors from data",
          "Data collection",
          "Data storage",
        ],
        correctAnswer: 1,
      },
      {
        id: 12,
        question: "What is a CSV file?",
        options: [
          "Computer System Virus",
          "Comma Separated Values file",
          "Code Security Validation",
          "Central Storage Volume",
        ],
        correctAnswer: 1,
      },
      {
        id: 13,
        question: "What is regression analysis?",
        options: [
          "Data storage method",
          "Predicting continuous values",
          "Data collection",
          "Database design",
        ],
        correctAnswer: 1,
      },
      {
        id: 14,
        question: "What is a data warehouse?",
        options: [
          "Hardware storage",
          "Central repository of integrated data",
          "Programming tool",
          "Network device",
        ],
        correctAnswer: 1,
      },
      {
        id: 15,
        question: "What is big data?",
        options: [
          "Large databases",
          "Extremely large datasets",
          "Fast computers",
          "Big files",
        ],
        correctAnswer: 1,
      },
      {
        id: 16,
        question: "What is scikit-learn?",
        options: [
          "Web framework",
          "Machine learning library for Python",
          "Database",
          "JavaScript library",
        ],
        correctAnswer: 1,
      },
      {
        id: 17,
        question: "What is TensorFlow?",
        options: [
          "Database system",
          "Machine learning framework",
          "Web server",
          "Programming language",
        ],
        correctAnswer: 1,
      },
      {
        id: 18,
        question: "What is data mining?",
        options: [
          "Data storage",
          "Discovering patterns in large datasets",
          "Data visualization",
          "Data collection",
        ],
        correctAnswer: 1,
      },
      {
        id: 19,
        question: "What is correlation?",
        options: [
          "Data storage",
          "Relationship between variables",
          "Data cleaning",
          "Database design",
        ],
        correctAnswer: 1,
      },
      {
        id: 20,
        question: "What is a dashboard?",
        options: [
          "Database tool",
          "Visual display of key information",
          "Programming interface",
          "Server monitor",
        ],
        correctAnswer: 1,
      },
    ],
    "DevOps Engineer": [
      {
        id: 1,
        question: "What is DevOps?",
        options: [
          "Development operations collaboration",
          "A programming language",
          "A database",
          "A framework",
        ],
        correctAnswer: 0,
      },
      {
        id: 2,
        question: "What is CI/CD?",
        options: [
          "Computer Interface/Code Development",
          "Continuous Integration/Continuous Deployment",
          "Centralized Infrastructure/Code Delivery",
          "Cloud Integration/Cloud Deployment",
        ],
        correctAnswer: 1,
      },
      {
        id: 3,
        question: "What is Docker?",
        options: [
          "A programming language",
          "Containerization platform",
          "Database system",
          "Web framework",
        ],
        correctAnswer: 1,
      },
      {
        id: 4,
        question: "What is Kubernetes?",
        options: [
          "Container orchestration platform",
          "Programming language",
          "Database",
          "Web server",
        ],
        correctAnswer: 0,
      },
      {
        id: 5,
        question: "What is Jenkins?",
        options: [
          "Database",
          "Automation server for CI/CD",
          "Programming language",
          "Container platform",
        ],
        correctAnswer: 1,
      },
      {
        id: 6,
        question: "What is AWS?",
        options: [
          "American Web Services",
          "Amazon Web Services",
          "Advanced Web System",
          "Application Web Server",
        ],
        correctAnswer: 1,
      },
      {
        id: 7,
        question: "What is infrastructure as code?",
        options: [
          "Hardware programming",
          "Managing infrastructure with code",
          "Database design",
          "Network cabling",
        ],
        correctAnswer: 1,
      },
      {
        id: 8,
        question: "What is a container?",
        options: [
          "Shipping box",
          "Lightweight, portable software package",
          "Database table",
          "Network device",
        ],
        correctAnswer: 1,
      },
      {
        id: 9,
        question: "What is Git used for?",
        options: [
          "Container management",
          "Version control",
          "Cloud computing",
          "Server monitoring",
        ],
        correctAnswer: 1,
      },
      {
        id: 10,
        question: "What is monitoring in DevOps?",
        options: [
          "Watching servers",
          "Tracking system performance",
          "Code review",
          "Database backup",
        ],
        correctAnswer: 1,
      },
      {
        id: 11,
        question: "What is Terraform?",
        options: [
          "Infrastructure as code tool",
          "Programming language",
          "Database",
          "Web framework",
        ],
        correctAnswer: 0,
      },
      {
        id: 12,
        question: "What is Ansible?",
        options: [
          "Configuration management tool",
          "Programming language",
          "Database",
          "Web server",
        ],
        correctAnswer: 0,
      },
      {
        id: 13,
        question: "What is cloud computing?",
        options: [
          "Weather system",
          "Delivering computing services over internet",
          "Local server management",
          "Desktop applications",
        ],
        correctAnswer: 1,
      },
      {
        id: 14,
        question: "What is load balancing?",
        options: [
          "Weight management",
          "Distributing network traffic",
          "Data backup",
          "Code optimization",
        ],
        correctAnswer: 1,
      },
      {
        id: 15,
        question: "What is a virtual machine?",
        options: [
          "Physical computer",
          "Software emulation of computer",
          "Database server",
          "Network switch",
        ],
        correctAnswer: 1,
      },
      {
        id: 16,
        question: "What is SSH?",
        options: [
          "Secure Shell protocol",
          "Super Server Host",
          "System Security Hardware",
          "Server Storage Hub",
        ],
        correctAnswer: 0,
      },
      {
        id: 17,
        question: "What is scaling?",
        options: [
          "Measuring weight",
          "Adjusting resources to handle load",
          "Code optimization",
          "Data compression",
        ],
        correctAnswer: 1,
      },
      {
        id: 18,
        question: "What is a pipeline in DevOps?",
        options: [
          "Water pipe",
          "Automated process for software delivery",
          "Network cable",
          "Database connection",
        ],
        correctAnswer: 1,
      },
      {
        id: 19,
        question: "What is logging?",
        options: [
          "Wood cutting",
          "Recording events in system",
          "Database backup",
          "Network setup",
        ],
        correctAnswer: 1,
      },
      {
        id: 20,
        question: "What is deployment?",
        options: [
          "Military term",
          "Releasing software to production",
          "Code writing",
          "Testing",
        ],
        correctAnswer: 1,
      },
    ],
    "Mobile App Developer": [
      {
        id: 1,
        question: "What is Android development?",
        options: [
          "Creating websites",
          "Building Android apps",
          "Database management",
          "Network setup",
        ],
        correctAnswer: 1,
      },
      {
        id: 2,
        question: "Which language is used for iOS development?",
        options: ["Java", "Swift", "Python", "C++"],
        correctAnswer: 1,
      },
      {
        id: 3,
        question: "What is React Native?",
        options: [
          "Database",
          "Framework for mobile apps using React",
          "Programming language",
          "Web server",
        ],
        correctAnswer: 1,
      },
      {
        id: 4,
        question: "What is Flutter?",
        options: [
          "UI toolkit for natively compiled apps",
          "Database",
          "Programming language",
          "Web framework",
        ],
        correctAnswer: 0,
      },
      {
        id: 5,
        question: "What is an APK file?",
        options: [
          "Android Package Kit",
          "Apple Program Kit",
          "Application Programming Key",
          "Advanced Program Kernel",
        ],
        correctAnswer: 0,
      },
      {
        id: 6,
        question: "What is Kotlin?",
        options: [
          "Programming language for Android",
          "Database",
          "Web framework",
          "Server software",
        ],
        correctAnswer: 0,
      },
      {
        id: 7,
        question: "What is Xcode?",
        options: [
          "IDE for macOS development",
          "Programming language",
          "Database",
          "Web server",
        ],
        correctAnswer: 0,
      },
      {
        id: 8,
        question: "What is a mobile SDK?",
        options: [
          "Software Development Kit for mobile",
          "System Development Key",
          "Server Data Kit",
          "Software Data Key",
        ],
        correctAnswer: 0,
      },
      {
        id: 9,
        question: "What is cross-platform development?",
        options: [
          "Developing for one platform",
          "Developing for multiple platforms",
          "Database development",
          "Web development",
        ],
        correctAnswer: 1,
      },
      {
        id: 10,
        question: "What is Firebase?",
        options: [
          "Mobile development platform by Google",
          "Programming language",
          "Database only",
          "Web server",
        ],
        correctAnswer: 0,
      },
      {
        id: 11,
        question: "What is an emulator?",
        options: [
          "Hardware device",
          "Software that mimics mobile device",
          "Programming language",
          "Database tool",
        ],
        correctAnswer: 1,
      },
      {
        id: 12,
        question: "What is SwiftUI?",
        options: [
          "Database framework",
          "UI framework for Apple platforms",
          "Web framework",
          "Server framework",
        ],
        correctAnswer: 1,
      },
      {
        id: 13,
        question: "What is Java used for in mobile?",
        options: [
          "Web development only",
          "Android app development",
          "iOS development",
          "Database only",
        ],
        correctAnswer: 1,
      },
      {
        id: 14,
        question: "What is push notification?",
        options: [
          "Email service",
          "Message sent to mobile device",
          "Database alert",
          "Network signal",
        ],
        correctAnswer: 1,
      },
      {
        id: 15,
        question: "What is app store optimization?",
        options: [
          "App development",
          "Improving app visibility in stores",
          "Code optimization",
          "Database optimization",
        ],
        correctAnswer: 1,
      },
      {
        id: 16,
        question: "What is Material Design?",
        options: [
          "Design system by Google",
          "Programming language",
          "Database design",
          "Network design",
        ],
        correctAnswer: 0,
      },
      {
        id: 17,
        question: "What is Android Studio?",
        options: [
          "Official IDE for Android",
          "Programming language",
          "Database",
          "Web server",
        ],
        correctAnswer: 0,
      },
      {
        id: 18,
        question: "What is a hybrid app?",
        options: [
          "Native app",
          "Web app in native container",
          "Database app",
          "Server app",
        ],
        correctAnswer: 1,
      },
      {
        id: 19,
        question: "What is app signing?",
        options: [
          "Autograph",
          "Digital certificate for app",
          "Code writing",
          "Database signing",
        ],
        correctAnswer: 1,
      },
      {
        id: 20,
        question: "What is app deployment?",
        options: [
          "App development",
          "Releasing app to store",
          "App testing",
          "App design",
        ],
        correctAnswer: 1,
      },
    ],
    default: [
      {
        id: 1,
        question: "What does HTML stand for?",
        options: [
          "Hyper Text Markup Language",
          "High Tech Modern Language",
          "Home Tool Markup Language",
          "Hyperlinks and Text Markup Language",
        ],
        correctAnswer: 0,
      },
      {
        id: 2,
        question: "Which language is used for styling web pages?",
        options: ["HTML", "Python", "CSS", "JavaScript"],
        correctAnswer: 2,
      },
      {
        id: 3,
        question: "What is the purpose of Git?",
        options: [
          "Database management",
          "Version control",
          "Web hosting",
          "Code compilation",
        ],
        correctAnswer: 1,
      },
      {
        id: 4,
        question: "What is programming?",
        options: [
          "Computer repair",
          "Creating software using code",
          "Network setup",
          "Hardware design",
        ],
        correctAnswer: 1,
      },
      {
        id: 5,
        question: "What does CPU stand for?",
        options: [
          "Central Processing Unit",
          "Computer Processing Unit",
          "Central Program Unit",
          "Computer Program Unit",
        ],
        correctAnswer: 0,
      },
      {
        id: 6,
        question: "What is an operating system?",
        options: [
          "Application software",
          "System software that manages hardware",
          "Programming language",
          "Database system",
        ],
        correctAnswer: 1,
      },
      {
        id: 7,
        question: "What is the internet?",
        options: [
          "Local network",
          "Global network of computers",
          "Computer hardware",
          "Software program",
        ],
        correctAnswer: 1,
      },
      {
        id: 8,
        question: "What is a web browser?",
        options: [
          "Search engine",
          "Software to access websites",
          "Website creator",
          "Email program",
        ],
        correctAnswer: 1,
      },
      {
        id: 9,
        question: "What is software?",
        options: [
          "Computer hardware",
          "Programs and applications",
          "Network cables",
          "Power supply",
        ],
        correctAnswer: 1,
      },
      {
        id: 10,
        question: "What is hardware?",
        options: [
          "Computer programs",
          "Physical components of computer",
          "Internet connection",
          "Software applications",
        ],
        correctAnswer: 1,
      },
      {
        id: 11,
        question: "What is a file?",
        options: [
          "Folder",
          "Container for storing information",
          "Program",
          "Network",
        ],
        correctAnswer: 1,
      },
      {
        id: 12,
        question: "What is a folder/directory?",
        options: [
          "File",
          "Container for organizing files",
          "Program",
          "Hardware",
        ],
        correctAnswer: 1,
      },
      {
        id: 13,
        question: "What is email?",
        options: [
          "Text message",
          "Electronic mail",
          "Phone call",
          "Fax",
        ],
        correctAnswer: 1,
      },
      {
        id: 14,
        question: "What is a password?",
        options: [
          "Username",
          "Secret word for authentication",
          "Email address",
          "File name",
        ],
        correctAnswer: 1,
      },
      {
        id: 15,
        question: "What is a website?",
        options: [
          "Computer program",
          "Collection of web pages",
          "Email service",
          "Network device",
        ],
        correctAnswer: 1,
      },
      {
        id: 16,
        question: "What is a search engine?",
        options: [
          "Web browser",
          "Tool for finding information online",
          "Email program",
          "Word processor",
        ],
        correctAnswer: 1,
      },
      {
        id: 17,
        question: "What is cloud storage?",
        options: [
          "Local hard drive",
          "Online file storage",
          "RAM memory",
          "CD/DVD",
        ],
        correctAnswer: 1,
      },
      {
        id: 18,
        question: "What is a smartphone?",
        options: [
          "Landline phone",
          "Mobile phone with computer features",
          "Desktop computer",
          "Tablet",
        ],
        correctAnswer: 1,
      },
      {
        id: 19,
        question: "What is social media?",
        options: [
          "Email service",
          "Online platforms for sharing content",
          "Search engine",
          "Web browser",
        ],
        correctAnswer: 1,
      },
      {
        id: 20,
        question: "What is e-commerce?",
        options: [
          "Email commerce",
          "Buying/selling goods online",
          "Social media",
          "Search engine",
        ],
        correctAnswer: 1,
      },
    ],
  },
  // Non-premium users के लिए कठिन प्रश्न
  "non-premium": {
    "Senior Software Engineer": [
      {
        id: 1,
        question:
          "What is the time complexity of QuickSort in the average case?",
        options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
        correctAnswer: 1,
      },
      {
        id: 2,
        question:
          "Which design pattern is used to create objects without specifying their concrete classes?",
        options: ["Singleton", "Factory", "Observer", "Strategy"],
        correctAnswer: 1,
      },
      {
        id: 3,
        question: "What does REST stand for in API architecture?",
        options: [
          "Remote Execution State Transfer",
          "Representational State Transfer",
          "Resource Execution State Transfer",
          "Remote State Transfer",
        ],
        correctAnswer: 1,
      },
      {
        id: 4,
        question: "What is the CAP theorem?",
        options: [
          "Consistency, Availability, Partition tolerance",
          "Consistency, Accessibility, Performance",
          "Concurrency, Availability, Partitioning",
          "Consistency, Authentication, Protocol",
        ],
        correctAnswer: 0,
      },
      {
        id: 5,
        question: "What is a microservices architecture?",
        options: [
          "Small independent services",
          "Monolithic application",
          "Single database system",
          "Client-server model",
        ],
        correctAnswer: 0,
      },
      {
        id: 6,
        question: "What is Docker used for?",
        options: [
          "Version control",
          "Containerization",
          "Code compilation",
          "Database management",
        ],
        correctAnswer: 1,
      },
      {
        id: 7,
        question: "What is Kubernetes?",
        options: [
          "Containerization platform",
          "Container orchestration",
          "Virtual machine",
          "Load balancer",
        ],
        correctAnswer: 1,
      },
      {
        id: 8,
        question: "What is the SOLID principle?",
        options: [
          "Software design principles",
          "Security protocols",
          "Database rules",
          "Network standards",
        ],
        correctAnswer: 0,
      },
      {
        id: 9,
        question: "What is Test-Driven Development?",
        options: [
          "Testing after development",
          "Writing tests before code",
          "Manual testing",
          "Automated deployment",
        ],
        correctAnswer: 1,
      },
      {
        id: 10,
        question: "What is CI/CD?",
        options: [
          "Code Integration/Code Deployment",
          "Continuous Integration/Continuous Deployment",
          "Continuous Inspection/Continuous Delivery",
          "Code Inspection/Code Delivery",
        ],
        correctAnswer: 1,
      },
      {
        id: 11,
        question: "What is the difference between SQL and NoSQL?",
        options: [
          "SQL is structured, NoSQL is unstructured",
          "SQL is faster",
          "NoSQL uses tables",
          "SQL is newer",
        ],
        correctAnswer: 0,
      },
      {
        id: 12,
        question: "What is a deadlock in concurrent programming?",
        options: [
          "Fast execution",
          "Two or more processes waiting forever",
          "Memory leak",
          "Network timeout",
        ],
        correctAnswer: 1,
      },
      {
        id: 13,
        question: "What is garbage collection?",
        options: [
          "Memory allocation",
          "Automatic memory management",
          "Data backup",
          "Code optimization",
        ],
        correctAnswer: 1,
      },
      {
        id: 14,
        question: "What is the difference between TCP and UDP?",
        options: [
          "TCP is connection-oriented, UDP is connectionless",
          "TCP is faster",
          "UDP is more reliable",
          "TCP is for video streaming",
        ],
        correctAnswer: 0,
      },
      {
        id: 15,
        question: "What is OAuth?",
        options: [
          "Programming language",
          "Authorization protocol",
          "Database system",
          "Web framework",
        ],
        correctAnswer: 1,
      },
      {
        id: 16,
        question: "What is the difference between symmetric and asymmetric encryption?",
        options: [
          "Symmetric uses one key, asymmetric uses two",
          "Symmetric is slower",
          "Asymmetric is for hashing",
          "Symmetric is for digital signatures",
        ],
        correctAnswer: 0,
      },
      {
        id: 17,
        question: "What is load balancing?",
        options: [
          "Distributing network traffic",
          "Code optimization",
          "Data compression",
          "Memory management",
        ],
        correctAnswer: 0,
      },
      {
        id: 18,
        question: "What is a distributed system?",
        options: [
          "Single computer system",
          "Multiple computers working together",
          "Local network",
          "Standalone application",
        ],
        correctAnswer: 1,
      },
      {
        id: 19,
        question: "What is eventual consistency?",
        options: [
          "Immediate consistency",
          "Consistency achieved over time",
          "No consistency",
          "Strong consistency",
        ],
        correctAnswer: 1,
      },
      {
        id: 20,
        question: "What is the difference between SOAP and REST?",
        options: [
          "SOAP is protocol, REST is architectural style",
          "SOAP is simpler",
          "REST requires XML",
          "SOAP is stateless",
        ],
        correctAnswer: 0,
      },
    ],
    "Full Stack Developer": [
      {
        id: 1,
        question: "Which of the following is NOT a JavaScript framework?",
        options: ["React", "Angular", "Django", "Vue"],
        correctAnswer: 2,
      },
      {
        id: 2,
        question: "What does CORS stand for?",
        options: [
          "Cross-Origin Resource Sharing",
          "Cross-Origin Request Security",
          "Core Origin Resource Sharing",
          "Cross-Origin Resource Security",
        ],
        correctAnswer: 0,
      },
      {
        id: 3,
        question: "Which database is NoSQL?",
        options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
        correctAnswer: 2,
      },
      {
        id: 4,
        question: "What is the virtual DOM in React?",
        options: [
          "Actual browser DOM",
          "Lightweight copy of real DOM",
          "Database object model",
          "Server-side DOM",
        ],
        correctAnswer: 1,
      },
      {
        id: 5,
        question: "What is JWT used for?",
        options: [
          "Database querying",
          "Authentication and authorization",
          "CSS styling",
          "HTML parsing",
        ],
        correctAnswer: 1,
      },
      {
        id: 6,
        question: "What is Redux used for?",
        options: [
          "State management in React",
          "Database management",
          "Server configuration",
          "CSS compilation",
        ],
        correctAnswer: 0,
      },
      {
        id: 7,
        question: "What is GraphQL?",
        options: [
          "Database language",
          "Query language for APIs",
          "Programming language",
          "CSS framework",
        ],
        correctAnswer: 1,
      },
      {
        id: 8,
        question: "What is WebSocket?",
        options: [
          "HTTP protocol",
          "Full-duplex communication protocol",
          "Database protocol",
          "Email protocol",
        ],
        correctAnswer: 1,
      },
      {
        id: 9,
        question: "What is server-side rendering?",
        options: [
          "Client-side rendering",
          "Rendering HTML on server",
          "Database rendering",
          "CSS rendering",
        ],
        correctAnswer: 1,
      },
      {
        id: 10,
        question: "What is a single-page application?",
        options: [
          "Multiple page application",
          "One HTML page with dynamic updates",
          "Static website",
          "Server-rendered app",
        ],
        correctAnswer: 1,
      },
      {
        id: 11,
        question: "What is TypeScript?",
        options: [
          "JavaScript superset with types",
          "New programming language",
          "CSS framework",
          "Database language",
        ],
        correctAnswer: 0,
      },
      {
        id: 12,
        question: "What is Next.js?",
        options: [
          "Backend framework",
          "React framework for production",
          "Database ORM",
          "CSS preprocessor",
        ],
        correctAnswer: 1,
      },
      {
        id: 13,
        question: "What is npm?",
        options: [
          "Node Package Manager",
          "New Programming Module",
          "Network Protocol Manager",
          "Node Process Manager",
        ],
        correctAnswer: 0,
      },
      {
        id: 14,
        question: "What is the difference between let, const, and var?",
        options: [
          "Scope and mutability differences",
          "No difference",
          "Performance differences",
          "Syntax differences",
        ],
        correctAnswer: 0,
      },
      {
        id: 15,
        question: "What is async/await in JavaScript?",
        options: [
          "Synchronous programming",
          "Asynchronous programming syntax",
          "Database query",
          "CSS property",
        ],
        correctAnswer: 1,
      },
      {
        id: 16,
        question: "What is middleware in Express.js?",
        options: [
          "Database layer",
          "Functions that have access to request/response",
          "Frontend component",
          "CSS processor",
        ],
        correctAnswer: 1,
      },
      {
        id: 17,
        question: "What is the difference between SQL injection and XSS?",
        options: [
          "SQL injection targets databases, XSS targets clients",
          "Both are same",
          "XSS targets databases",
          "SQL injection targets clients",
        ],
        correctAnswer: 0,
      },
      {
        id: 18,
        question: "What is Docker Compose?",
        options: [
          "Container orchestration",
          "Tool for multi-container Docker apps",
          "Containerization platform",
          "Virtual machine manager",
        ],
        correctAnswer: 1,
      },
      {
        id: 19,
        question: "What is the difference between HTTP/1.1 and HTTP/2?",
        options: [
          "HTTP/2 has multiplexing",
          "HTTP/1.1 is faster",
          "HTTP/2 is text-based",
          "No difference",
        ],
        correctAnswer: 0,
      },
      {
        id: 20,
        question: "What is a Webpack?",
        options: [
          "JavaScript framework",
          "Module bundler",
          "Database tool",
          "CSS framework",
        ],
        correctAnswer: 1,
      },
    ],
    "Data Scientist": [
      {
        id: 1,
        question: "What is the difference between supervised and unsupervised learning?",
        options: [
          "Supervised uses labeled data, unsupervised doesn't",
          "Supervised is faster",
          "Unsupervised requires labels",
          "Both are same",
        ],
        correctAnswer: 0,
      },
      {
        id: 2,
        question: "What is overfitting in machine learning?",
        options: [
          "Model performs well on training data but poorly on new data",
          "Model performs poorly on training data",
          "Model is too simple",
          "Model is perfectly balanced",
        ],
        correctAnswer: 0,
      },
      {
        id: 3,
        question: "What is cross-validation?",
        options: [
          "Data cleaning technique",
          "Model evaluation technique",
          "Data visualization method",
          "Feature engineering",
        ],
        correctAnswer: 1,
      },
      {
        id: 4,
        question: "What is the curse of dimensionality?",
        options: [
          "Too few features",
          "Problems with high-dimensional data",
          "Small datasets",
          "Simple models",
        ],
        correctAnswer: 1,
      },
      {
        id: 5,
        question: "What is regularization in machine learning?",
        options: [
          "Data normalization",
          "Preventing overfitting",
          "Feature selection",
          "Data augmentation",
        ],
        correctAnswer: 1,
      },
      {
        id: 6,
        question: "What is a confusion matrix?",
        options: [
          "Data visualization",
          "Table for classification performance",
          "Data cleaning tool",
          "Statistical test",
        ],
        correctAnswer: 1,
      },
      {
        id: 7,
        question: "What is gradient descent?",
        options: [
          "Optimization algorithm",
          "Data collection method",
          "Statistical test",
          "Data visualization",
        ],
        correctAnswer: 0,
      },
      {
        id: 8,
        question: "What is the difference between precision and recall?",
        options: [
          "Precision: true positives/predicted positives, Recall: true positives/actual positives",
          "Both are same",
          "Precision is for regression",
          "Recall is for classification only",
        ],
        correctAnswer: 0,
      },
      {
        id: 9,
        question: "What is feature engineering?",
        options: [
          "Creating new features from existing data",
          "Data cleaning",
          "Model training",
          "Data collection",
        ],
        correctAnswer: 0,
      },
      {
        id: 10,
        question: "What is PCA?",
        options: [
          "Principal Component Analysis for dimensionality reduction",
          "Data collection method",
          "Classification algorithm",
          "Data cleaning",
        ],
        correctAnswer: 0,
      },
      {
        id: 11,
        question: "What is a neural network?",
        options: [
          "Computer network",
          "Machine learning model inspired by brain",
          "Database system",
          "Statistical method",
        ],
        correctAnswer: 1,
      },
      {
        id: 12,
        question: "What is deep learning?",
        options: [
          "Machine learning with neural networks",
          "Data mining",
          "Statistical analysis",
          "Data visualization",
        ],
        correctAnswer: 0,
      },
      {
        id: 13,
        question: "What is transfer learning?",
        options: [
          "Transferring data",
          "Using pre-trained models",
          "Data transformation",
          "Model deployment",
        ],
        correctAnswer: 1,
      },
      {
        id: 14,
        question: "What is NLP?",
        options: [
          "Natural Language Processing",
          "Network Layer Protocol",
          "New Learning Process",
          "Neural Language Programming",
        ],
        correctAnswer: 0,
      },
      {
        id: 15,
        question: "What is a decision tree?",
        options: [
          "Flowchart-like model",
          "Linear model",
          "Statistical test",
          "Data structure",
        ],
        correctAnswer: 0,
      },
      {
        id: 16,
        question: "What is ensemble learning?",
        options: [
          "Using multiple models",
          "Single model training",
          "Data preprocessing",
          "Feature extraction",
        ],
        correctAnswer: 0,
      },
      {
        id: 17,
        question: "What is k-means clustering?",
        options: [
          "Classification algorithm",
          "Unsupervised clustering algorithm",
          "Regression algorithm",
          "Dimensionality reduction",
        ],
        correctAnswer: 1,
      },
      {
        id: 18,
        question: "What is time series analysis?",
        options: [
          "Analyzing time-stamped data",
          "Real-time analysis",
          "Database analysis",
          "Network analysis",
        ],
        correctAnswer: 0,
      },
      {
        id: 19,
        question: "What is bias-variance tradeoff?",
        options: [
          "Balance between underfitting and overfitting",
          "Data bias",
          "Model variance",
          "Statistical error",
        ],
        correctAnswer: 0,
      },
      {
        id: 20,
        question: "What is A/B testing?",
        options: [
          "Comparing two versions",
          "Automated testing",
          "Backup testing",
          "Algorithm testing",
        ],
        correctAnswer: 0,
      },
    ],
    "DevOps Engineer": [
      {
        id: 1,
        question: "What is Infrastructure as Code?",
        options: [
          "Hardware programming",
          "Managing infrastructure using code",
          "Database programming",
          "Network coding",
        ],
        correctAnswer: 1,
      },
      {
        id: 2,
        question: "What is blue-green deployment?",
        options: [
          "Deployment strategy with two environments",
          "Cloud deployment",
          "Database deployment",
          "Network deployment",
        ],
        correctAnswer: 0,
      },
      {
        id: 3,
        question: "What is canary deployment?",
        options: [
          "Full deployment",
          "Gradual rollout to subset of users",
          "Database migration",
          "Network upgrade",
        ],
        correctAnswer: 1,
      },
      {
        id: 4,
        question: "What is a pod in Kubernetes?",
        options: [
          "Smallest deployable unit",
          "Virtual machine",
          "Container image",
          "Network service",
        ],
        correctAnswer: 0,
      },
      {
        id: 5,
        question: "What is Helm in Kubernetes?",
        options: [
          "Package manager",
          "Container runtime",
          "Network plugin",
          "Storage system",
        ],
        correctAnswer: 0,
      },
      {
        id: 6,
        question: "What is Prometheus?",
        options: [
          "Database system",
          "Monitoring and alerting toolkit",
          "Container platform",
          "CI/CD tool",
        ],
        correctAnswer: 1,
      },
      {
        id: 7,
        question: "What is Grafana?",
        options: [
          "Container orchestration",
          "Data visualization and monitoring",
          "Version control",
          "Infrastructure as code",
        ],
        correctAnswer: 1,
      },
      {
        id: 8,
        question: "What is the difference between Docker and Kubernetes?",
        options: [
          "Docker is for containers, Kubernetes orchestrates them",
          "Both are same",
          "Kubernetes creates containers",
          "Docker orchestrates containers",
        ],
        correctAnswer: 0,
      },
      {
        id: 9,
        question: "What is a service mesh?",
        options: [
          "Network infrastructure layer",
          "Database layer",
          "Application layer",
          "Security layer",
        ],
        correctAnswer: 0,
      },
      {
        id: 10,
        question: "What is Istio?",
        options: [
          "Service mesh",
          "Container runtime",
          "Monitoring tool",
          "CI/CD tool",
        ],
        correctAnswer: 0,
      },
      {
        id: 11,
        question: "What is GitOps?",
        options: [
          "Git operations",
          "Operations by Git pull request",
          "Version control",
          "Code management",
        ],
        correctAnswer: 1,
      },
      {
        id: 12,
        question: "What is a serverless architecture?",
        options: [
          "No servers required",
          "Cloud provider manages servers",
          "On-premise servers",
          "Virtual servers",
        ],
        correctAnswer: 1,
      },
      {
        id: 13,
        question: "What is AWS Lambda?",
        options: [
          "Serverless compute service",
          "Database service",
          "Storage service",
          "Networking service",
        ],
        correctAnswer: 0,
      },
      {
        id: 14,
        question: "What is Terraform state?",
        options: [
          "Current infrastructure state",
          "Future infrastructure plan",
          "Code state",
          "Network state",
        ],
        correctAnswer: 0,
      },
      {
        id: 15,
        question: "What is a CI/CD pipeline?",
        options: [
          "Automated software delivery process",
          "Manual deployment process",
          "Testing process only",
          "Development process",
        ],
        correctAnswer: 0,
      },
      {
        id: 16,
        question: "What is horizontal vs vertical scaling?",
        options: [
          "Horizontal adds more machines, vertical adds resources",
          "Both are same",
          "Vertical adds more machines",
          "Horizontal adds resources",
        ],
        correctAnswer: 0,
      },
      {
        id: 17,
        question: "What is a reverse proxy?",
        options: [
          "Client-side proxy",
          "Server-side proxy handling client requests",
          "Database proxy",
          "Network proxy",
        ],
        correctAnswer: 1,
      },
      {
        id: 18,
        question: "What is immutable infrastructure?",
        options: [
          "Infrastructure that never changes",
          "Replace servers instead of modifying",
          "Static infrastructure",
          "Fixed infrastructure",
        ],
        correctAnswer: 1,
      },
      {
        id: 19,
        question: "What is a circuit breaker pattern?",
        options: [
          "Electrical circuit",
          "Fault tolerance pattern",
          "Network pattern",
          "Security pattern",
        ],
        correctAnswer: 1,
      },
      {
        id: 20,
        question: "What is a secrets manager?",
        options: [
          "Password storage",
          "Secure storage for sensitive data",
          "User management",
          "Access management",
        ],
        correctAnswer: 1,
      },
    ],
    "Mobile App Developer": [
      {
        id: 1,
        question: "What is the difference between native and hybrid apps?",
        options: [
          "Native uses platform-specific languages, hybrid uses web technologies",
          "Both are same",
          "Hybrid is faster",
          "Native uses web technologies",
        ],
        correctAnswer: 0,
      },
      {
        id: 2,
        question: "What is React Native bridge?",
        options: [
          "Network bridge",
          "Communication between JS and native threads",
          "Database bridge",
          "Server bridge",
        ],
        correctAnswer: 1,
      },
      {
        id: 3,
        question: "What is a Progressive Web App?",
        options: [
          "Native app",
          "Web app with native-like features",
          "Mobile website",
          "Desktop app",
        ],
        correctAnswer: 1,
      },
      {
        id: 4,
        question: "What is SwiftUI?",
        options: [
          "UIKit replacement",
          "Declarative UI framework",
          "Database framework",
          "Networking library",
        ],
        correctAnswer: 1,
      },
      {
        id: 5,
        question: "What is Flutter's widget tree?",
        options: [
          "Database structure",
          "Hierarchy of UI components",
          "Network structure",
          "File structure",
        ],
        correctAnswer: 1,
      },
      {
        id: 6,
        question: "What is Android Jetpack?",
        options: [
          "Suite of libraries",
          "Programming language",
          "Database",
          "Network protocol",
        ],
        correctAnswer: 0,
      },
      {
        id: 7,
        question: "What is Kotlin Coroutines?",
        options: [
          "Asynchronous programming",
          "Database operations",
          "Network requests only",
          "UI programming",
        ],
        correctAnswer: 0,
      },
      {
        id: 8,
        question: "What is MVVM architecture?",
        options: [
          "Model-View-ViewModel",
          "Model-View-Controller",
          "Mobile View Model",
          "Main View Model",
        ],
        correctAnswer: 0,
      },
      {
        id: 9,
        question: "What is dependency injection?",
        options: [
          "Code injection",
          "Providing objects to a class",
          "Database injection",
          "Network injection",
        ],
        correctAnswer: 1,
      },
      {
        id: 10,
        question: "What is unit testing in mobile development?",
        options: [
          "Testing entire app",
          "Testing individual units/components",
          "UI testing",
          "Network testing",
        ],
        correctAnswer: 1,
      },
      {
        id: 11,
        question: "What is App Store Connect?",
        options: [
          "App development tool",
          "Apple's platform for app management",
          "App testing tool",
          "App design tool",
        ],
        correctAnswer: 1,
      },
      {
        id: 12,
        question: "What is Google Play Console?",
        options: [
          "Game console",
          "Google's platform for Android app management",
          "Development IDE",
          "Testing tool",
        ],
        correctAnswer: 1,
      },
      {
        id: 13,
        question: "What is code signing?",
        options: [
          "Code commenting",
          "Digital signature for app",
          "Code formatting",
          "Code optimization",
        ],
        correctAnswer: 1,
      },
      {
        id: 14,
        question: "What is fastlane?",
        options: [
          "App development tool",
          "Automation tool for app deployment",
          "Testing framework",
          "UI design tool",
        ],
        correctAnswer: 1,
      },
      {
        id: 15,
        question: "What is the difference between iOS and Android app lifecycle?",
        options: [
          "Different state management",
          "Same lifecycle",
          "iOS has no lifecycle",
          "Android has no lifecycle",
        ],
        correctAnswer: 0,
      },
      {
        id: 16,
        question: "What is ARCore/ARKit?",
        options: [
          "Augmented Reality platforms",
          "Database tools",
          "Network libraries",
          "UI frameworks",
        ],
        correctAnswer: 0,
      },
      {
        id: 17,
        question: "What is mobile app security best practices?",
        options: [
          "No security needed",
          "Secure data storage, network calls, etc.",
          "Only network security",
          "Only data security",
        ],
        correctAnswer: 1,
      },
      {
        id: 18,
        question: "What is offline-first app design?",
        options: [
          "App works without internet",
          "App needs constant internet",
          "Online-only app",
          "Cloud-based app",
        ],
        correctAnswer: 0,
      },
      {
        id: 19,
        question: "What is mobile app performance optimization?",
        options: [
          "Only UI optimization",
          "Memory, battery, network optimization",
          "Only network optimization",
          "Only battery optimization",
        ],
        correctAnswer: 1,
      },
      {
        id: 20,
        question: "What is mobile CI/CD?",
        options: [
          "Continuous Integration/Deployment for mobile",
          "App development",
          "App testing only",
          "App design",
        ],
        correctAnswer: 0,
      },
    ],
    default: [
      {
        id: 1,
        question: "What is the time complexity of binary search?",
        options: ["O(n)", "O(log n)", "O(n²)", "O(1)"],
        correctAnswer: 1,
      },
      {
        id: 2,
        question: "Which of these is a relational database?",
        options: ["MongoDB", "Redis", "PostgreSQL", "Cassandra"],
        correctAnswer: 2,
      },
      {
        id: 3,
        question: "What is the purpose of Docker?",
        options: [
          "Version control",
          "Containerization",
          "Code compilation",
          "Database management",
        ],
        correctAnswer: 1,
      },
      {
        id: 4,
        question: "What is React used for?",
        options: [
          "Backend development",
          "Building user interfaces",
          "Database design",
          "Mobile app development (only)",
        ],
        correctAnswer: 1,
      },
      {
        id: 5,
        question: "What does SQL stand for?",
        options: [
          "Structured Query Language",
          "Simple Query Language",
          "Standard Query Language",
          "System Query Language",
        ],
        correctAnswer: 0,
      },
      {
        id: 6,
        question: "What is the difference between HTTP and HTTPS?",
        options: [
          "HTTPS is secure",
          "HTTP is faster",
          "No difference",
          "HTTPS is for email",
        ],
        correctAnswer: 0,
      },
      {
        id: 7,
        question: "What is a framework in programming?",
        options: [
          "Programming language",
          "Pre-built structure for developing software",
          "Database system",
          "Operating system",
        ],
        correctAnswer: 1,
      },
      {
        id: 8,
        question: "What is version control?",
        options: [
          "Code compilation",
          "Tracking changes to code",
          "Database versioning",
          "Network control",
        ],
        correctAnswer: 1,
      },
      {
        id: 9,
        question: "What is an algorithm?",
        options: [
          "Programming language",
          "Step-by-step procedure for solving problems",
          "Hardware component",
          "Database query",
        ],
        correctAnswer: 1,
      },
      {
        id: 10,
        question: "What is object-oriented programming?",
        options: [
          "Procedural programming",
          "Programming based on objects",
          "Functional programming",
          "Declarative programming",
        ],
        correctAnswer: 1,
      },
      {
        id: 11,
        question: "What is a data structure?",
        options: [
          "Data type",
          "Way to organize and store data",
          "Database table",
          "File format",
        ],
        correctAnswer: 1,
      },
      {
        id: 12,
        question: "What is cloud computing?",
        options: [
          "Local computing",
          "Delivering computing services over internet",
          "Personal computer",
          "Server room",
        ],
        correctAnswer: 1,
      },
      {
        id: 13,
        question: "What is machine learning?",
        options: [
          "Manual programming",
          "AI that enables learning from data",
          "Data entry",
          "Database management",
        ],
        correctAnswer: 1,
      },
      {
        id: 14,
        question: "What is a protocol in networking?",
        options: [
          "Hardware device",
          "Set of rules for communication",
          "Software program",
          "Database rule",
        ],
        correctAnswer: 1,
      },
      {
        id: 15,
        question: "What is a compiler?",
        options: [
          "Program that translates code",
          "Text editor",
          "Database",
          "Web browser",
        ],
        correctAnswer: 0,
      },
      {
        id: 16,
        question: "What is an IDE?",
        options: [
          "Internet Development Engine",
          "Integrated Development Environment",
          "Interactive Design Environment",
          "Integrated Design Engine",
        ],
        correctAnswer: 1,
      },
      {
        id: 17,
        question: "What is a function in programming?",
        options: [
          "Variable",
          "Reusable block of code",
          "Data type",
          "Database table",
        ],
        correctAnswer: 1,
      },
      {
        id: 18,
        question: "What is a variable?",
        options: [
          "Fixed value",
          "Storage location with name",
          "Function",
          "Class",
        ],
        correctAnswer: 1,
      },
      {
        id: 19,
        question: "What is debugging?",
        options: [
          "Writing code",
          "Finding and fixing errors",
          "Designing UI",
          "Testing hardware",
        ],
        correctAnswer: 1,
      },
      {
        id: 20,
        question: "What is a loop in programming?",
        options: [
          "Conditional statement",
          "Repeating block of code",
          "Variable declaration",
          "Function call",
        ],
        correctAnswer: 1,
      },
    ],
  },
};
