// services/excel.service.js
import ExcelJS from "exceljs";
import Contact from "../../models/contact.model.js";
import EarlyAccess from "../../models/earlyAccess.model.js";
import Requirement from "../../models/requirement.model.js";

// Models map and precise column configuration map matching your exact schema keys
const modelMapping = {
  contacts: Contact,
  earlyaccess: EarlyAccess,
  requirements: Requirement
};

const columnConfigurations = {
  contacts: [
    { header: "ID", key: "_id", width: 25 },
    { header: "Name", key: "name", width: 20 },
    { header: "Email", key: "email", width: 25 },
    { header: "Phone", key: "phone", width: 15 },
    { header: "Category", key: "category", width: 20 },
    { header: "Subject", key: "subject", width: 25 },
    { header: "Description", key: "description", width: 35 },
    { header: "Status", key: "status", width: 15 },
    { header: "Attachment URL", key: "attachment_url", width: 30 },
    { header: "Created At", key: "createdAt", width: 20 }
  ],
  earlyaccess: [
    { header: "ID", key: "_id", width: 25 },
    { header: "Name", key: "name", width: 20 },
    { header: "Email", key: "email", width: 25 },
    { header: "Stage", key: "stage", width: 15 },
    { header: "Created At", key: "createdAt", width: 20 }
  ],
  requirements: [
    { header: "ID", key: "_id", width: 25 },
    { header: "Name", key: "name", width: 20 },
    { header: "Email", key: "email", width: 25 },
    { header: "Phone", key: "phone", width: 15 },
    { header: "Institution Name", key: "institutionName", width: 25 },
    { header: "Role", key: "role", width: 15 },
    { header: "Requirement", key: "requirement", width: 30 },
    { header: "Institution Type", key: "institutionType", width: 20 },
    { header: "Team Size", key: "teamSize", width: 12 },
    { header: "Message", key: "message", width: 30 },
    { header: "Source URL", key: "sourceUrl", width: 25 },
    { header: "Page Title", key: "pageTitle", width: 20 },
    { header: "Campaign Source", key: "campaignSource", width: 20 },
    { header: "Device Type", key: "deviceType", width: 15 },
    { header: "Country", key: "country", width: 15 },
    { header: "User IP", key: "userip", width: 15 },
    { header: "Created At", key: "createdAt", width: 20 }
  ]
};

/**
 * Universal dynamic excel exporter matching exact database attributes
 */
export const exportCollectionToExcel = async (type) => {
  const Model = modelMapping[type.toLowerCase()];
  const columns = columnConfigurations[type.toLowerCase()];
  
  if (!Model || !columns) throw new Error("Invalid schema model targeted for extraction");

  const documents = await Model.find().sort({ createdAt: -1 });
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet(`All ${type}`);

  worksheet.columns = columns;

  documents.forEach((doc) => {
    const rowData = {};
    columns.forEach((col) => {
      if (col.key === "attachment_url") {
        rowData[col.key] = doc.attachment?.url || "N/A";
      } else if (doc[col.key] instanceof Date) {
        rowData[col.key] = doc[col.key].toLocaleString();
      } else {
        rowData[col.key] = doc[col.key] || "N/A";
      }
    });
    worksheet.addRow(rowData);
  });

  // Match the exact premium layout theme (#0013E3) of your dashboard
  worksheet.getRow(1).eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFF" }, name: "Segoe UI" };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "0013E3" }
    };
  });

  return workbook;
};

/**
 * Universal database mass importer from upload streams
 */
export const importExcelToCollection = async (type, buffer) => {
  const Model = modelMapping[type.toLowerCase()];
  const columns = columnConfigurations[type.toLowerCase()];
  if (!Model || !columns) throw new Error("Invalid target mapping configuration");

  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer);
  const worksheet = workbook.getWorksheet(1);

  const batchInsertData = [];
  
  // Skip row 1 because it contains header names
  worksheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber === 1) return; 

    const docObject = {};
    columns.forEach((col, idx) => {
      const cellValue = row.getCell(idx + 1).value;
      // Filter out unique database autogenerated IDs on fresh imports
      if (col.key === "_id") return; 
      
      if (cellValue !== "N/A" && cellValue !== undefined) {
        docObject[col.key] = cellValue;
      }
    });

    batchInsertData.push(docObject);
  });

  if (batchInsertData.length === 0) throw new Error("No clean document rows encountered");

  // Handle updates or bulk inserts safely depending on the unique constraints (e.g. EarlyAccess email)
  if (type.toLowerCase() === "earlyaccess") {
    for (const user of batchInsertData) {
      await Model.updateOne({ email: user.email.toLowerCase() }, user, { upsert: true });
    }
    return { inserted: batchInsertData.length };
  }

  return await Model.insertMany(batchInsertData);
};